variables:
  IMAGE_NAME: "registry.inqbeo.de/zabbix-dev/zabbix-server-create-upgrade-db"

stages:
- build
- manifest

.build_x86_64_template:
  tags:
  - k8s
  - nonpriv
  - amd64
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  retry: 2
  script:
  - mkdir -p /kaniko/.docker
  - echo ${DOCKERCFG_HARBOR} > /kaniko/.docker/config.json
  - MYDATE=${CI_JOB_STARTED_AT%T*}
  - >-
    /kaniko/executor --context "${CI_PROJECT_DIR}" --build-arg "RUNNER_ARCH=amd64" --build-arg "MAJOR_VERSION=${MAJOR_VERSION}" --dockerfile "${CI_PROJECT_DIR}/Dockerfile" --destination "${IMAGE_NAME}:${CI_PIPELINE_ID}-${MAJOR_VERSION}-amd64" --verbosity info #magic___^_^___line #magic___^_^___line #magic___^_^___line

.build_arm64_template:
  tags:
  - k8s
  - nonpriv
  - arm64
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
  - mkdir -p /kaniko/.docker
  - echo ${DOCKERCFG_HARBOR} > /kaniko/.docker/config.json
  - MYDATE=${CI_JOB_STARTED_AT%T*}
  - >-
    /kaniko/executor --context "${CI_PROJECT_DIR}" --build-arg "RUNNER_ARCH=arm64" --build-arg "MAJOR_VERSION=${MAJOR_VERSION}" --dockerfile "${CI_PROJECT_DIR}/Dockerfile" --destination "${IMAGE_NAME}:${CI_PIPELINE_ID}-${MAJOR_VERSION}-arm64" --verbosity info #magic___^_^___line #magic___^_^___line #magic___^_^___line

.create_manifest_template:
  tags:
  - k8s
  - nonpriv
  - arm64
  stage: manifest
  image:
    name: curlimages/curl
  before_script:
  - curl -s -L https://github.com/estesp/manifest-tool/releases/download/v2.1.6/binaries-manifest-tool-2.1.6.tar.gz | tar xvz
  - mv manifest-tool-linux-arm64 manifest-tool
  - chmod +x manifest-tool
  script:
  - echo "Creating manifest for MAJOR_VERSION=$MAJOR_VERSION"
  - mkdir ~/.docker
  - echo ${DOCKERCFG_HARBOR} > ~/.docker/config.json
  - ./manifest-tool --docker-cfg ~/.docker/config.json push from-args --platforms linux/amd64,linux/arm64 --template ${IMAGE_NAME}:${CI_PIPELINE_ID}-${MAJOR_VERSION}-ARCH --target ${IMAGE_NAME}:${MAJOR_VERSION}-latest
  - ./manifest-tool --docker-cfg ~/.docker/config.json inspect ${IMAGE_NAME}:${MAJOR_VERSION}-latest

# Matrix builds for architectures
build_x86_64:
  stage: build
  parallel:
    matrix:
      - MAJOR_VERSION: "6.0"
      - MAJOR_VERSION: "6.4"
      - MAJOR_VERSION: "7.0"
  extends: .build_x86_64_template

build_arm64:
  stage: build
  parallel:
    matrix:
      - MAJOR_VERSION: "6.0"
      - MAJOR_VERSION: "6.4"
      - MAJOR_VERSION: "7.0"
  extends: .build_arm64_template

create_manifest:
  stage: manifest
  parallel:
    matrix:
      - MAJOR_VERSION: "6.0"
      - MAJOR_VERSION: "6.4"
      - MAJOR_VERSION: "7.0"
  extends: .create_manifest_template
